export const languages = {
    es: {
      nativeName: 'Español',
      options: 'Opciones',
      changeLanguage: 'Cambiar Idioma',
      changeMode: 'Cambiar Modo',
      darkMode: 'Modo Oscuro',
      lightMode: 'Modo Claro',
      changeConversionMode: 'Cambiar Modo de Conversión',
      useComma: 'Usar Coma',
      usePoint: 'Usar Punto',
      changeMoneySymbol: 'Cambiar Símbolo de Moneda',
      inventoryManagement: 'Gestión de Inventario',
      products: 'Productos',
      totalCost: 'Costo Total',
      totalSellingPrice: 'Precio de Venta Total',
      recommendation: 'Recomendación: Añade productos para ver el análisis',
      noProducts: 'No hay productos',
      save: 'Guardar',
      load: 'Cargar',
      saveData: 'Guardar Datos',
      fileName: 'Nombre del Archivo',
      loadData: 'Cargar Datos',
      noSavedFiles: 'No hay archivos guardados',
      addProduct: 'Añadir Producto',
      productName: 'Nombre del Producto',
      quantity: 'Cantidad',
      cost: 'Costo',
      sellingPrice: 'Precio de Venta',
      add: 'Añadir',
      editProduct: 'Editar Producto',
      confirmDeletion: 'Confirmar Eliminación',
      deleteProductConfirmation: '¿Estás seguro de que quieres eliminar este producto?',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      error: 'Error',
      enterFileName: 'Por favor, ingresa un nombre de archivo',
      dataSavedSuccessfully: 'Datos guardados exitosamente',
      failedToSaveData: 'Error al guardar los datos',
      noDataForFile: 'No hay datos para este archivo',
      failedToLoadFile: 'Error al cargar el archivo',
      searchProducts: 'Buscar productos',
      profitTotal: 'Ganancia Total',
      lossTotal: 'Pérdida Total',
      neutralBalance: 'Balance Neutro',
      edit: 'Editar',
      totalProductCost: 'Costo Total del Producto',
      totalProductSellingPrice: 'Precio Total de Venta del Producto',
      productProfit: 'Ganancia del Producto',
      productLoss: 'Pérdida del Producto',
      productNeutralBalance: 'Saldo del Producto Neutro',
      initialBalance: 'Saldo Inicial',
      date: 'Fecha',
      description: 'Descripción',
      income: 'Ingresos',
      expenses: 'Egresos',
      dailyBalance: 'Saldo Diario',
      totalBalance: 'Saldo Total',
      actions: 'Acciones',
      noEntries: 'No hay entradas. Agrega una para comenzar.',
      addEntry: 'Agregar Entrada',
      editEntry: 'Editar Entrada',
      confirmDeleteEntry: '¿Estás seguro de que quieres eliminar esta entrada?',
      confirmDeleteFile: '¿Estás seguro de que quieres eliminar',
      addToBalance: 'Agregar al Balance',
      balanceManagement: 'Gestión de Balance',
      rotationRecommendation: 'Gire su dispositivo para una mejor experiencia.',
      fileDeletedSuccessfully: 'Archivo eliminado exitosamente',
      failedToDeleteFile: 'Error al eliminar el archivo',
      fillAllFields: 'Por favor, completa todos los campos.',
      noDataForFile: 'No hay datos para este archivo',
      failedToLoadFile: 'Error al cargar el archivo',
      success: 'Éxito',
    },
    en: {
      nativeName: 'English',
      options: 'Options',
      changeLanguage: 'Change Language',
      changeMode: 'Change Mode',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      changeConversionMode: 'Change Conversion Mode',
      useComma: 'Use Comma',
      usePoint: 'Use Point',
      changeMoneySymbol: 'Change Money Symbol',
      inventoryManagement: 'Inventory Management',
      products: 'Products',
      totalCost: 'Total Cost',
      totalSellingPrice: 'Total Selling Price',
      recommendation: 'Recommendation: Add products to see analysis',
      noProducts: 'No products',
      save: 'Save',
      load: 'Load',
      saveData: 'Save Data',
      fileName: 'File Name',
      loadData: 'Load Data',
      noSavedFiles: 'No saved files',
      addProduct: 'Add Product',
      productName: 'Product Name',
      quantity: 'Quantity',
      cost: 'Cost',
      sellingPrice: 'Selling Price',
      add: 'Add',
      editProduct: 'Edit Product',
      confirmDeletion: 'Confirm Deletion',
      deleteProductConfirmation: 'Are you sure you want to delete this product?',
      cancel: 'Cancel',
      delete: 'Delete',
      error: 'Error',
      enterFileName: 'Please enter a file name',
      dataSavedSuccessfully: 'Data saved successfully',
      failedToSaveData: 'Failed to save data',
      noDataForFile: 'No data for this file',
      failedToLoadFile: 'Failed to load file',
      searchProducts: 'Search products',
      profitTotal: 'Total Profit',
      lossTotal: 'Total Loss',
      neutralBalance: 'Neutral Balance',
      edit: 'Edit',
      totalProductCost: 'Total Product Cost',
      totalProductSellingPrice: 'Total Product Selling Price',
      productProfit: 'Product Profit',
      productLoss: 'Product Loss',
      productNeutralBalance: 'Neutral Product Balance',
      initialBalance: 'Initial Balance',
      date: 'Date',
      description: 'Description',
      income: 'Income',
      expenses: 'Expenses',
      dailyBalance: 'Daily Balance',
      totalBalance: 'Total Balance',
      actions: 'Actions',
      noEntries: 'No entries. Add one to start.',
      addEntry: 'Add Entry',
      editEntry: 'Edit Entry',
      confirmDeleteEntry: 'Are you sure you want to delete this entry?',
      confirmDeleteFile: 'Are you sure you want to delete',
      addToBalance: 'Add to Balance',
      balanceManagement: 'Balance Management',
      rotationRecommendation: 'Rotate your device for a better experience.',
      fileDeletedSuccessfully: 'File deleted successfully',
      failedToDeleteFile: 'Failed to delete file',
      fillAllFields: 'Please fill in all fields.',
      noDataForFile: 'No data for this file',
      failedToLoadFile: 'Failed to load file',
      success: 'Success',
    },
    pt: {
      nativeName: 'Português',
      options: 'Opções',
      changeLanguage: 'Mudar Idioma',
      changeMode: 'Mudar Modo',
      darkMode: 'Modo Escuro',
      lightMode: 'Modo Claro',
      changeConversionMode: 'Mudar Modo de Conversão',
      useComma: 'Usar Vírgula',
      usePoint: 'Usar Ponto',
      changeMoneySymbol: 'Mudar Símbolo de Moeda',
      inventoryManagement: 'Gestão de Inventário',
      products: 'Produtos',
      totalCost: 'Custo Total',
      totalSellingPrice: 'Preço de Venda Total',
      recommendation: 'Recomendação: Adicione produtos para ver a análise',
      noProducts: 'Sem produtos',
      save: 'Salvar',
      load: 'Carregar',
      saveData: 'Salvar Dados',
      fileName: 'Nome do Arquivo',
      loadData: 'Carregar Dados',
      noSavedFiles: 'Nenhum arquivo salvo',
      addProduct: 'Adicionar Produto',
      productName: 'Nome do Produto',
      quantity: 'Quantidade',
      cost: 'Custo',
      sellingPrice: 'Preço de Venda',
      add: 'Adicionar',
      editProduct: 'Editar Produto',
      confirmDeletion: 'Confirmar Exclusão',
      deleteProductConfirmation: 'Tem certeza que deseja excluir este produto?',
      cancel: 'Cancelar',
      delete: 'Excluir',
      error: 'Erro',
      enterFileName: 'Por favor, insira um nome de arquivo',
      dataSavedSuccessfully: 'Dados salvos com sucesso',
      failedToSaveData: 'Falha ao salvar dados',
      noDataForFile: 'Nenhum dado para este arquivo',
      failedToLoadFile: 'Falha ao carregar arquivo',
      searchProducts: 'Pesquisar produtos',
      profitTotal: 'Lucro Total',
      lossTotal: 'Prejuízo Total',
      neutralBalance: 'Balanço Neutro',
      edit: 'Editar',
      totalProductCost: 'Custo Total do Produto',
      totalProductSellingPrice: 'Preço Total de Venda do Produto',
      productProfit: 'Lucro do Produto',
      productLoss: 'Prejuízo do Produto',
      productNeutralBalance: 'Saldo do Produto Neutro',
      initialBalance: 'Saldo Inicial',
      date: 'Data',
      description: 'Descrição',
      income: 'Receitas',
      expenses: 'Despesas',
      dailyBalance: 'Saldo Diário',
      totalBalance: 'Saldo Total',
      actions: 'Ações',
      noEntries: 'Sem entradas. Adicione uma para começar.',
      addEntry: 'Adicionar Entrada',
      editEntry: 'Editar Entrada',
      confirmDeleteEntry: 'Tem certeza que deseja excluir esta entrada?',
      confirmDeleteFile: 'Tem certeza que deseja excluir',
      addToBalance: 'Adicionar ao Balanço',
      balanceManagement: 'Gestão de Balanço',
      rotationRecommendation: 'Gire seu dispositivo para uma melhor experiência.',
      fileDeletedSuccessfully: 'Arquivo deletado com sucesso',
      failedToDeleteFile: 'Falha ao deletar o arquivo',
      fillAllFields: 'Por favor, complete todos os campos.',
      noDataForFile: 'Nenhum dado para este arquivo',
      failedToLoadFile: 'Falha ao carregar arquivo',
      success: 'Sucesso',
    },
    fr: {
      nativeName: 'Français',
      options: 'Options',
      changeLanguage: 'Changer de Langue',
      changeMode: 'Changer de Mode',
      darkMode: 'Mode Sombre',
      lightMode: 'Mode Clair',
      changeConversionMode: 'Changer le Mode de Conversion',
      useComma: 'Utiliser la Virgule',
      usePoint: 'Utiliser le Point',
      changeMoneySymbol: 'Changer le Symbole Monétaire',
      inventoryManagement: 'Gestion des Stocks',
      products: 'Produits',
      totalCost: 'Coût Total',
      totalSellingPrice: 'Prix de Vente Total',
      recommendation: 'Recommandation : Ajoutez des produits pour voir l\'analyse',
      noProducts: 'Aucun produit',
      save: 'Enregistrer',
      load: 'Charger',
      saveData: 'Enregistrer les Données',
      fileName: 'Nom du Fichier',
      loadData: 'Charger les Données',
      noSavedFiles: 'Aucun fichier enregistré',
      addProduct: 'Ajouter un Produit',
      productName: 'Nom du Produit',
      quantity: 'Quantité',
      cost: 'Coût',
      sellingPrice: 'Prix de Vente',
      add: 'Ajouter',
      editProduct: 'Modifier le Produit',
      confirmDeletion: 'Confirmer la Suppression',
      deleteProductConfirmation: 'Êtes-vous sûr de vouloir supprimer ce produit ?',
      cancel: 'Annuler',
      delete: 'Supprimer',
      error: 'Erreur',
      enterFileName: 'Veuillez entrer un nom de fichier',
      dataSavedSuccessfully: 'Données enregistrées avec succès',
      failedToSaveData: 'Échec de l\'enregistrement des données',
      noDataForFile: 'Aucune donnée pour ce fichier',
      failedToLoadFile: 'Échec du chargement du fichier',
      searchProducts: 'Rechercher des produits',
      profitTotal: 'Bénéfice Total',
      lossTotal: 'Perte Totale',
      neutralBalance: 'Solde Neutre',
      edit: 'Modifier',
      totalProductCost: 'Coût Total du Produit',
      totalProductSellingPrice: 'Prix de Vente Total du Produit',
      productProfit: 'Bénéfice du Produit',
      productLoss: 'Perte du Produit',
      productNeutralBalance: 'Solde du Produit Neutre',
      initialBalance: 'Solde Initial',
      date: 'Date',
      description: 'Description',
      income: 'Revenus',
      expenses: 'Dépenses',
      dailyBalance: 'Solde Journalier',
      totalBalance: 'Solde Total',
      actions: 'Actions',
      noEntries: 'Aucune entrée. Ajoutez-en une pour commencer.',
      addEntry: 'Ajouter une Entrée',
      editEntry: 'Modifier l\'Entrée',
      confirmDeleteEntry: 'Êtes-vous sûr de vouloir supprimer cette entrée ?',
      confirmDeleteFile: 'Êtes-vous sûr de vouloir supprimer',
      addToBalance: 'Ajouter au Bilan',
      balanceManagement: 'Gestion de Bilan',
      rotationRecommendation: 'Girez votre appareil pour une meilleure expérience.',
      fileDeletedSuccessfully: 'Fichier supprimé avec succès',
      failedToDeleteFile: 'Erreur lors de la suppression du fichier',
      fillAllFields: 'Veuillez remplir tous les champs.',
      noDataForFile: 'Aucune donnée pour ce fichier',
      failedToLoadFile: 'Échec du chargement du fichier',
      success: 'Succès',
    },
    it: {
      nativeName: 'Italiano',
      options: 'Opzioni',
      changeLanguage: 'Cambia Lingua',
      changeMode: 'Cambia Modalità',
      darkMode: 'Modalità Scura',
      lightMode: 'Modalità Chiara',
      changeConversionMode: 'Cambia Modalità di Conversione',
      useComma: 'Usa la Virgola',
      usePoint: 'Usa il Punto',
      changeMoneySymbol: 'Cambia Simbolo Valuta',
      inventoryManagement: 'Gestione Inventario',
      products: 'Prodotti',
      totalCost: 'Costo Totale',
      totalSellingPrice: 'Prezzo di Vendita Totale',
      recommendation: 'Raccomandazione: Aggiungi prodotti per vedere l\'analisi',
      noProducts: 'Nessun prodotto',
      save: 'Salva',
      load: 'Carica',
      saveData: 'Salva Dati',
      fileName: 'Nome del File',
      loadData: 'Carica Dati',
      noSavedFiles: 'Nessun file salvato',
      addProduct: 'Aggiungi Prodotto',
      productName: 'Nome del Prodotto',
      quantity: 'Quantità',
      cost: 'Costo',
      sellingPrice: 'Prezzo di Vendita',
      add: 'Aggiungi',
      editProduct: 'Modifica Prodotto',
      confirmDeletion: 'Conferma Eliminazione',
      deleteProductConfirmation: 'Sei sicuro di voler eliminare questo prodotto?',
      cancel: 'Annulla',
      delete: 'Elimina',
      error: 'Errore',
      enterFileName: 'Inserisci un nome per il file',
      dataSavedSuccessfully: 'Dati salvati con successo',
      failedToSaveData: 'Impossibile salvare i dati',
      noDataForFile: 'Nessun dato per questo file',
      failedToLoadFile: 'Impossibile caricare il file',
      searchProducts: 'Cerca prodotti',
      profitTotal: 'Profitto Totale',
      lossTotal: 'Perdita Totale',
      neutralBalance: 'Bilancio Neutro',
      edit: 'Modifica',
      totalProductCost: 'Costo Totale del Prodotto',
      totalProductSellingPrice: 'Prezzo di Vendita Totale del Prodotto',
      productProfit: 'Profitto del Prodotto',
      productLoss: 'Perdita del Prodotto',
      productNeutralBalance: 'Saldo del Prodotto Neutro',
      initialBalance: 'Saldo Iniziale',
      date: 'Data',
      description: 'Descrizione',
      income: 'Entrate',
      expenses: 'Uscite',
      dailyBalance: 'Saldo Giornaliero',
      totalBalance: 'Saldo Totale',
      actions: 'Azioni',
      noEntries: 'Nessuna voce. Aggiungine una per iniziare.',
      addEntry: 'Aggiungi Voce',
      editEntry: 'Modifica Voce',
      confirmDeleteEntry: 'Sei sicuro di voler eliminare questa voce?',
      confirmDeleteFile: 'Sei sicuro di voler eliminare',
      addToBalance: 'Aggiungi al Bilancio',
      balanceManagement: 'Gestione di Bilancio',
      rotationRecommendation: 'Girez il tuo dispositivo per una migliore esperienza.',
      fileDeletedSuccessfully: 'File eliminato con successo',
      failedToDeleteFile: 'Errore durante la cancellazione del file',
      fillAllFields: 'Per favore, completa tutti i campi.',
      noDataForFile: 'Nessun dato per questo file',
      failedToLoadFile: 'Impossibile caricare il file',
      success: 'Successo',
    },
    de: {
      nativeName: 'Deutsch',
      options: 'Optionen',
      changeLanguage: 'Sprache ändern',
      changeMode: 'Modus ändern',
      darkMode: 'Dunkler Modus',
      lightMode: 'Heller Modus',
      changeConversionMode: 'Konvertierungsmodus ändern',
      useComma: 'Komma verwenden',
      usePoint: 'Punkt verwenden',
      changeMoneySymbol: 'Währungssymbol ändern',
      inventoryManagement: 'Bestandsverwaltung',
      products: 'Produkte',
      totalCost: 'Gesamtkosten',
      totalSellingPrice: 'Gesamtverkaufspreis',
      recommendation: 'Empfehlung: Fügen Sie Produkte hinzu, um die Analyse zu sehen',
      noProducts: 'Keine Produkte',
      save: 'Speichern',
      load: 'Laden',
      saveData: 'Daten speichern',
      fileName: 'Dateiname',
      loadData: 'Daten laden',
      noSavedFiles: 'Keine gespeicherten Dateien',
      addProduct: 'Produkt hinzufügen',
      productName: 'Produktname',
      quantity: 'Menge',
      cost: 'Kosten',
      sellingPrice: 'Verkaufspreis',
      add: 'Hinzufügen',
      editProduct: 'Produkt bearbeiten',
      confirmDeletion: 'Löschen bestätigen',
      deleteProductConfirmation: 'Sind Sie sicher, dass Sie dieses Produkt löschen möchten?',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      error: 'Fehler',
      enterFileName: 'Bitte geben Sie einen Dateinamen ein',
      dataSavedSuccessfully: 'Daten erfolgreich gespeichert',
      failedToSaveData: 'Fehler beim Speichern der Daten',
      noDataForFile: 'Keine Daten für diese Datei',
      failedToLoadFile: 'Fehler beim Laden der Datei',
      searchProducts: 'Produkte suchen',
      profitTotal: 'Gesamtgewinn',
      lossTotal: 'Gesamtverlust',
      neutralBalance: 'Neutrale Bilanz',
      edit: 'Bearbeiten',
      totalProductCost: 'Gesamtkosten des Produkts',
      totalProductSellingPrice: 'Gesamtverkaufspreis des Produkts',
      productProfit: 'Produktgewinn',
      productLoss: 'Produktverlust',
      productNeutralBalance: 'Neutraler Produktsaldo',
      initialBalance: 'Anfangssaldo',
      date: 'Datum',
      description: 'Beschreibung',
      income: 'Einnahmen',
      expenses: 'Ausgaben',
      dailyBalance: 'Tagessaldo',
      totalBalance: 'Gesamtsaldo',
      actions: 'Aktionen',
      noEntries: 'Keine Einträge. Fügen Sie einen hinzu, um zu beginnen.',
      addEntry: 'Eintrag hinzufügen',
      editEntry: 'Eintrag bearbeiten',
      confirmDeleteEntry: 'Sind Sie sicher, dass Sie diesen Eintrag löschen möchten?',
      confirmDeleteFile: 'Sind Sie sicher, dass Sie löschen möchten',
      addToBalance: 'Zum Saldo hinzufügen',
      balanceManagement: 'Bilanzverwaltung',
      rotationRecommendation: 'Girez Ihr Gerät für eine bessere Erfahrung.',
      fileDeletedSuccessfully: 'Datei erfolgreich gelöscht',
      failedToDeleteFile: 'Fehler beim Löschen der Datei',
      fillAllFields: 'Bitte füllen Sie alle Felder aus.',
      noDataForFile: 'Keine Daten für diese Datei',
      failedToLoadFile: 'Fehler beim Laden der Datei',
      success: 'Erfolg',
    },
  };